# Generated by Django 3.2.19 on 2023-05-19 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('universidad', models.CharField(max_length=45, verbose_name='Universidad')),
                ('cantFisica', models.IntegerField(verbose_name='Cant. Fisica')),
                ('cantIntelectual', models.IntegerField(verbose_name='Cant. Intelectual')),
                ('cantSensorial', models.IntegerField(verbose_name='Cant. Sensorial')),
                ('cantMental', models.IntegerField(verbose_name='Cant. Mental')),
                ('cantMasculino', models.IntegerField(verbose_name='Cant. Masculino')),
                ('cantFemenino', models.IntegerField(verbose_name='Cant. Femenino')),
                ('cantTotal', models.IntegerField(verbose_name='Total')),
            ],
        ),
    ]
