# Generated by Django 3.2.19 on 2023-05-23 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infoEDEU', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='cantTotal',
            field=models.IntegerField(null=True, verbose_name='Total'),
        ),
    ]
